name: Docker Image CI/CD

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행
  # 필요에 따라 다른 트리거(예: PR, 태그 등)를 설정할 수 있습니다.

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions에서 사용할 환경 (Ubuntu)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 리포지토리 코드를 체크아웃

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secrets에 저장된 Docker Hub 사용자 이름
        password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secrets에 저장된 Docker Hub 비밀번호

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Buildx 설정 (다양한 플랫폼 지원)

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .  # Dockerfile이 위치한 디렉토리
        push: true  # 이미지를 Docker Hub에 푸시
        tags: k4sud0n/huffy:latest  # 태그를 지정
